(()=>{'use strict';
const KEY='roadToP1MediaV100';
const WEB_API='https://road-to-p1-media-api.felix-bruno1973.workers.dev';
const PUBLISH_KEY_STORAGE='roadToP1MediaPublishKey';
const $=id=>document.getElementById(id);
const now=()=>new Date().toISOString();
const today=()=>new Date().toISOString().slice(0,10);
const fd=v=>v?new Date(v).toLocaleDateString('fr-FR'):'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let D={reports:[],web:[],training:[],activity:[],deployments:[],wpPages:[],wpLastSync:null};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)D=Object.assign(D,x)}catch(e){}}
function save(){localStorage.setItem(KEY,JSON.stringify(D));renderHome()}
function uid(p='m'){return p+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function toast(x){const e=$('toast');e.textContent=x;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1800)}
function log(text){D.activity.unshift({at:now(),text});D.activity=D.activity.slice(0,30)}
function getPublishKey(){let k=sessionStorage.getItem(PUBLISH_KEY_STORAGE)||'';if(!k){k=(prompt('Code de publication ROAD TO P1 :')||'').trim();if(k)sessionStorage.setItem(PUBLISH_KEY_STORAGE,k)}return k}
function isHomeMobileSpacingChange(x){const t=[x.page,x.title,x.desc].join(' ').toLowerCase();const home=String(x.wpPageId||'')==='10'||t.includes('accueil');return home&&/(mobile|téléphone|telephone)/.test(t)&&/(espace|espacement|vide|noir|hauteur|logo)/.test(t)}
async function applySupportedWebChanges(items){const supported=items.filter(isHomeMobileSpacingChange);if(!supported.length)return {published:0,supported:0};const key=getPublishKey();if(!key)throw new Error('Code de publication requis.');const r=await fetch(WEB_API+'/apply-home-mobile-spacing',{method:'POST',headers:{'Content-Type':'application/json','X-RTP1-Key':key},body:'{}'});const data=await r.json().catch(()=>({}));if(r.status===401||r.status===403){sessionStorage.removeItem(PUBLISH_KEY_STORAGE);throw new Error('Code de publication incorrect.')}if(!r.ok||!data.ok)throw new Error(data.message||'Publication WordPress refusée.');const stamp=now();supported.forEach(x=>{x.status='Publié';x.published=stamp});return {published:supported.length,supported:supported.length,result:data}}

async function loadOfficialLogo(){
 const img=$('officialLogo');
 const urls=['https://felixbruno1973-design.github.io/road-to-p1-dynamics/','https://felixbruno1973-design.github.io/road-to-p1-dynamics/road_to_p1_dynamics_phase1_v1.0.59.html'];
 for(const url of urls){try{const r=await fetch(url);if(!r.ok)continue;const html=await r.text(),doc=new DOMParser().parseFromString(html,'text/html'),src=doc.querySelector('.official-logo')?.getAttribute('src');if(src){img.src=src.startsWith('data:')?src:new URL(src,url).href;return}}catch(e){}}
 img.alt='ROAD TO P1';
}
const titles={home:['Media Center','Créer, publier et entraîner les pilotes à communiquer.'],reports:['Reports','Créer et gérer les contenus ROAD TO P1.'],web:['Web Design','Préparer et suivre les évolutions de road-to-p1.com.'],training:['Media Training','Préparer Lara et Aaron aux interviews françaises et internationales.']};
function openView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('view-'+v).classList.add('active');$('pageTitle').textContent=titles[v][0];$('pageSubtitle').textContent=titles[v][1];if(v==='reports')renderReports();if(v==='web')renderWeb();if(v==='training')renderTraining()}
function renderHome(){$('homeReports').textContent=D.reports.length;$('homeWeb').textContent=D.web.filter(x=>x.status!=='Terminé').length;$('homeTraining').textContent=D.training.length;const a=$('recentActivity');a.innerHTML=D.activity.length?D.activity.slice(0,8).map(x=>`<div class="activity-item"><b>${esc(x.text)}</b><span>${fd(x.at)}</span></div>`).join(''):'<div class="empty">Aucune activité enregistrée pour le moment.</div>'}
function reportTemplate(pilot,type,event,angle){const e=event||'ce week-end de course',a=angle?` ${angle.trim()}`:'';if(type==='Rapport de course')return `${pilot} — Rapport de course\n\nÉvénement : ${e}\n\nRésumé\nUne nouvelle étape de progression pour ${pilot} sous les couleurs de ROAD TO P1.${a}\n\nPoints clés\n• Performance et évolution\n• Travail réalisé avec l’équipe\n• Enseignements pour la prochaine course\n\nMerci à nos partenaires pour leur soutien.`;if(type==='Communiqué partenaires')return `Bonjour,\n\nROAD TO P1 vous partage le bilan de ${e} avec ${pilot}. Cette course s’inscrit dans notre projet d’accompagnement de jeunes pilotes vers le haut niveau et d’égalité des chances dans le sport automobile.${a}\n\nMerci pour votre confiance et votre soutien.\n\nROAD TO P1`;if(type==='Story')return `${pilot} • ${e}\n\n🏁 Une nouvelle étape.\n📈 Du travail, de la progression, de l’expérience.\n❤️ Merci à tous ceux qui accompagnent ROAD TO P1.${a}`;if(type==='Reel / vidéo courte')return `SCRIPT REEL — ${pilot} / ${e}\n\n0–3 s : départ / action forte\n3–8 s : séquences piste + paddock\n8–13 s : résultat ou progression clé\n13–18 s : ${pilot} face caméra\n18–22 s : partenaires + logo ROAD TO P1\n\nTexte écran : « Chaque tour nous rapproche du prochain objectif. »${a}`;return `🏁 ${pilot} poursuit sa progression avec ROAD TO P1 à ${e}.\n\nUn week-end riche en travail, en apprentissage et en expérience.${a}\n\nMerci à toutes les personnes et partenaires qui rendent cette aventure possible.\n\n#RoadToP1 #Karting #Motorsport #YoungDrivers`;}
function renderReports(){const q=($('repSearch')?.value||'').toLowerCase(),L=D.reports.filter(x=>!q||[x.pilot,x.type,x.event,x.status].join(' ').toLowerCase().includes(q));$('repCount').textContent=`${L.length} contenu${L.length>1?'s':''}`;$('repList').innerHTML=L.length?L.map(x=>`<div class="list-item"><div><h4>${esc(x.event||x.type)}</h4><div class="list-meta">${esc(x.pilot)} • ${esc(x.type)} • ${fd(x.date||x.created)}</div><p>${esc((x.text||'').slice(0,150))}${(x.text||'').length>150?'…':''}</p></div><div class="mini-actions"><span class="pill ${x.status==='Publié'?'done':x.status==='Validé'?'valid':''}">${esc(x.status)}</span><button data-rep-open="${x.id}">Ouvrir</button><button class="danger" data-rep-del="${x.id}">Supprimer</button></div></div>`).join(''):'<div class="empty">Aucun contenu enregistré.</div>';document.querySelectorAll('[data-rep-open]').forEach(b=>b.onclick=()=>openReport(b.dataset.repOpen));document.querySelectorAll('[data-rep-del]').forEach(b=>b.onclick=()=>delReport(b.dataset.repDel))}
function openReport(id){const x=D.reports.find(x=>x.id===id);if(!x)return;$('repPilot').value=x.pilot;$('repType').value=x.type;$('repEvent').value=x.event;$('repDate').value=x.date||'';$('repStatus').value=x.status;$('repAngle').value=x.angle||'';$('repText').value=x.text||'';$('repSave').dataset.edit=id;$('repFileNote').textContent=x.files?.length?`Médias mémorisés : ${x.files.join(', ')}`:'Aucun média mémorisé.';toast('Contenu chargé.')}
function delReport(id){if(!confirm('Supprimer ce contenu ?'))return;D.reports=D.reports.filter(x=>x.id!==id);log('Contenu Reports supprimé');save();renderReports()}
function saveReport(){const id=$('repSave').dataset.edit||uid('r'),files=[...($('repFiles').files||[])].map(f=>f.name),old=D.reports.find(x=>x.id===id);const x={id,pilot:$('repPilot').value,type:$('repType').value,event:$('repEvent').value.trim(),date:$('repDate').value,status:$('repStatus').value,angle:$('repAngle').value.trim(),text:$('repText').value,files:files.length?files:(old?.files||[]),created:old?.created||now(),updated:now()};const i=D.reports.findIndex(x=>x.id===id);i>=0?D.reports[i]=x:D.reports.unshift(x);log(`${i>=0?'Contenu mis à jour':'Nouveau contenu'} • ${x.pilot} • ${x.type}`);delete $('repSave').dataset.edit;save();renderReports();toast('Contenu enregistré.')}
function populateWebPageSelect(){const sel=$('webPage');if(!sel)return;const pages=D.wpPages||[];if(!pages.length)return;const current=sel.value;sel.innerHTML='<option value="">Choisir une page WordPress…</option>'+pages.map(p=>`<option value="${esc(p.title||'(Sans titre)')}" data-wp-id="${esc(p.id)}" data-wp-slug="${esc(p.slug||'')}">${esc(p.title||'(Sans titre)')} — /${esc(p.slug||'')}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current}
function selectWpPage(id){const p=(D.wpPages||[]).find(x=>String(x.id)===String(id));if(!p)return;populateWebPageSelect();$('webPage').value=p.title||'(Sans titre)';$('webPage').dataset.wpId=p.id;$('webPage').dataset.wpSlug=p.slug||'';$('webTitle').value=`Modifier la page ${p.title||'(Sans titre)'}`;$('webTitle').focus();document.querySelector('#view-web .web-grid')?.scrollIntoView({behavior:'smooth',block:'start'});toast(`Page sélectionnée : ${p.title||'(Sans titre)'}`)}
function renderWpPages(){const box=$('webPages'),count=$('webPagesCount');if(!box||!count)return;const pages=D.wpPages||[];populateWebPageSelect();count.textContent=pages.length?`${pages.length} page${pages.length>1?'s':''} • ${D.wpLastSync?new Date(D.wpLastSync).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):''}`:'Non synchronisé';box.innerHTML=pages.length?pages.map(p=>`<div class="wp-page-item"><div><h4>${esc(p.title||'(Sans titre)')}</h4><div class="list-meta">ID ${esc(p.id)} • /${esc(p.slug||'')} • ${esc(p.status||'—')}</div><p>Dernière modification : ${p.modified?new Date(p.modified).toLocaleString('fr-FR'):'—'}</p></div><div class="mini-actions"><button data-wp-work="${esc(p.id)}">Travailler</button><a class="wp-open" href="${esc(p.link||'https://road-to-p1.com')}" target="_blank" rel="noopener">Voir ↗</a></div></div>`).join(''):'<div class="empty">Cliquez sur « Synchroniser le site » pour lire les pages du vrai road-to-p1.com.</div>';document.querySelectorAll('[data-wp-work]').forEach(b=>b.onclick=()=>selectWpPage(b.dataset.wpWork))}
async function syncWordPressPages(){const btn=$('webSync'),status=$('webConnectionStatus'),detail=$('webConnectionDetail'),dot=$('webConnectionDot');btn.disabled=true;btn.textContent='Synchronisation…';status.textContent='Connexion en cours…';detail.textContent='Lecture de WordPress via Cloudflare';dot.className='connection-dot pending';try{const health=await fetch(WEB_API+'/health',{cache:'no-store'});const h=await health.json();if(!health.ok||!h.ok)throw new Error(h.message||'Connexion WordPress impossible');const r=await fetch(WEB_API+'/pages',{cache:'no-store'});const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.message||'Lecture des pages impossible');D.wpPages=Array.isArray(data.pages)?data.pages:[];D.wpLastSync=now();log(`WordPress synchronisé • ${D.wpPages.length} page${D.wpPages.length>1?'s':''}`);save();renderWpPages();status.textContent='WordPress connecté';detail.textContent=`${D.wpPages.length} page${D.wpPages.length>1?'s':''} lue${D.wpPages.length>1?'s':''} • accès en lecture seule`;dot.className='connection-dot connected';toast('Site WordPress synchronisé.')}catch(e){status.textContent='Connexion à vérifier';detail.textContent=e.message||'Erreur de synchronisation';dot.className='connection-dot error';toast('Synchronisation impossible.')}finally{btn.disabled=false;btn.textContent='Synchroniser le site'}}
function renderWeb(){const pending=D.web.filter(x=>x.status!=='Terminé'&&x.status!=='Publié');renderWpPages();$('webCount').textContent=`${D.web.length} demande${D.web.length>1?'s':''}`;$('webList').innerHTML=D.web.length?D.web.map(x=>`<div class="list-item"><div><h4>${esc(x.title)}</h4><div class="list-meta">${esc(x.page)} • Priorité ${esc(x.priority)} • ${fd(x.created)}</div><p>${esc(x.desc||'')}</p></div><div class="mini-actions"><span class="pill ${x.status==='Terminé'||x.status==='Publié'?'done':x.status.includes('Validé')?'valid':x.priority==='Haute'?'high':''}">${esc(x.status)}</span>${x.status!=='Terminé'&&x.status!=='Publié'?`<button data-web-done="${x.id}">Terminé</button>`:''}<button class="danger" data-web-del="${x.id}">Supprimer</button></div></div>`).join(''):'<div class="empty">Aucune modification enregistrée.</div>';if($('webDeployHint'))$('webDeployHint').textContent=pending.length?`${pending.length} modification${pending.length>1?'s':''} à vérifier avant publication.`:'Aucune modification en attente.';if($('webDeployStart'))$('webDeployStart').disabled=!pending.length;document.querySelectorAll('[data-web-done]').forEach(b=>b.onclick=()=>{const x=D.web.find(x=>x.id===b.dataset.webDone);if(x){x.status='Terminé';x.done=now();log(`Modification Web terminée • ${x.title}`);save();renderWeb()}});document.querySelectorAll('[data-web-del]').forEach(b=>b.onclick=()=>{if(!confirm('Supprimer cette demande ?'))return;D.web=D.web.filter(x=>x.id!==b.dataset.webDel);save();renderWeb()})}
function saveWeb(){const title=$('webTitle').value.trim();if(!title)return toast('Ajoutez un titre.');const sel=$('webPage'),opt=sel.selectedOptions?.[0];const wpId=sel.dataset.wpId||opt?.dataset?.wpId||null,wpSlug=sel.dataset.wpSlug||opt?.dataset?.wpSlug||'';const x={id:uid('w'),page:sel.value,wpPageId:wpId,wpSlug,priority:$('webPriority').value,title,desc:$('webDesc').value.trim(),status:'À préparer',created:now()};D.web.unshift(x);log(`Nouvelle modification Web • ${title}`);$('webTitle').value='';$('webDesc').value='';delete sel.dataset.wpId;delete sel.dataset.wpSlug;save();renderWeb();toast('Modification ajoutée.')}
let webDeployStep=1,webDeployIds=[];
function webDeployChanges(){return webDeployIds.map(id=>D.web.find(x=>x.id===id)).filter(Boolean)}
function openWebDeploy(){const pending=D.web.filter(x=>x.status!=='Terminé'&&x.status!=='Publié');if(!pending.length)return toast('Aucune modification à publier.');webDeployIds=pending.map(x=>x.id);webDeployStep=1;$('webDeployModal').classList.add('show');$('webDeployModal').setAttribute('aria-hidden','false');renderWebDeploy()}
function closeWebDeploy(){$('webDeployModal').classList.remove('show');$('webDeployModal').setAttribute('aria-hidden','true');webDeployIds=[];webDeployStep=1}
function deployList(items){return `<div class="deploy-list">${items.map(x=>`<div class="deploy-item"><div><b>${esc(x.title)}</b><span>${esc(x.page)} • Priorité ${esc(x.priority)}</span></div><span class="pill ${x.priority==='Haute'?'high':''}">${esc(x.status)}</span></div>`).join('')}</div>`}
function renderWebDeploy(){const items=webDeployChanges();document.querySelectorAll('[data-deploy-step]').forEach(x=>x.classList.toggle('active',Number(x.dataset.deployStep)===webDeployStep));$('webDeployPrev').style.visibility=webDeployStep===1?'hidden':'visible';$('webDeployCancel').textContent=webDeployStep===4?'Fermer':'Annuler';let html='';if(webDeployStep===1){$('webDeployTitle').textContent='1. Vérification des modifications';html=`<p class="deploy-lead">${items.length} modification${items.length>1?'s':''} seront intégrées au prochain lot de mise à jour.</p>${deployList(items)}<div class="deploy-note">Vérifiez les pages, les priorités et le contenu avant de continuer.</div>`; $('webDeployNext').textContent='Continuer vers l’aperçu';$('webDeployNext').disabled=false}else if(webDeployStep===2){$('webDeployTitle').textContent='2. Aperçu du lot';html=`<p class="deploy-lead">Voici le lot qui sera soumis à validation.</p>${deployList(items)}<div class="deploy-preview"><b>Site actuel</b><span>road-to-p1.com</span><a class="btn ghost" href="https://road-to-p1.com" target="_blank" rel="noopener">Ouvrir le site actuel ↗</a><small>L’aperçu visuel des changements sera activé quand Media sera connecté au système de déploiement du site.</small></div>`; $('webDeployNext').textContent='Continuer vers la validation';$('webDeployNext').disabled=false}else if(webDeployStep===3){$('webDeployTitle').textContent='3. Validation finale';html=`<p class="deploy-lead">Confirmez que ce lot est prêt à être transmis au processus de publication.</p>${deployList(items)}<label class="deploy-confirm"><input type="checkbox" id="webDeployConfirm"> <span>Je confirme avoir vérifié ces modifications et je valide ce lot pour publication.</span></label>`; $('webDeployNext').textContent='Valider';$('webDeployNext').disabled=false}else{$('webDeployTitle').textContent='4. Publication';const auto=items.some(isHomeMobileSpacingChange);html=`<div class="deploy-ready"><div class="ready-icon">✓</div><h4>${auto?'Prêt à publier':'Lot validé'}</h4><p>${auto?'La modification reconnue sera appliquée au vrai site après confirmation.':'Les modifications sont validées.'}</p><div class="deploy-note ${auto?'':'warning'}"><b>${auto?'Publication automatique active :':'Publication automatique partielle :'}</b> ${auto?'Accueil mobile — réduction de la hauteur du premier écran à 55 vh.':'Cette demande n’est pas encore une opération automatisée.'}</div></div>`; $('webDeployNext').textContent=auto?'Publier sur road-to-p1.com':'Enregistrer le lot validé';$('webDeployNext').disabled=false}}
async function nextWebDeploy(){if(webDeployStep===3&&!$('webDeployConfirm')?.checked)return toast('Confirmez la validation du lot.');if(webDeployStep<4){webDeployStep++;renderWebDeploy();return}const items=webDeployChanges(),stamp=now();items.forEach(x=>{if(x.status!=='Publié'){x.status='Validé pour publication';x.validated=stamp}});$('webDeployNext').disabled=true;$('webDeployNext').textContent='Publication…';try{const pub=await applySupportedWebChanges(items);D.deployments.unshift({id:uid('d'),created:stamp,status:pub.published?'Publié':'Validé pour publication',changeIds:items.map(x=>x.id),count:items.length,published:pub.published});D.deployments=D.deployments.slice(0,50);log(pub.published?`Site mis à jour • ${pub.published} modification${pub.published>1?'s':''}`:`Lot Web validé • ${items.length} modification${items.length>1?'s':''}`);save();renderWeb();closeWebDeploy();toast(pub.published?'Site WordPress mis à jour.':'Lot validé pour publication.')}catch(e){toast(e.message||'Publication impossible.');renderWebDeploy()}}
function prevWebDeploy(){if(webDeployStep>1){webDeployStep--;renderWebDeploy()}}
const QUESTIONS={fr:{race:['Comment résumerais-tu ta course en trois phrases ?','Quel a été le moment le plus difficile de ton week-end ?','De quoi es-tu le plus satisfait aujourd’hui ?','Qu’as-tu appris pendant cette course ?','Quel est ton objectif pour la prochaine épreuve ?','Comment expliques-tu ta progression aujourd’hui ?'],sponsor:['Que représente le soutien des partenaires pour ton projet ?','Comment présenterais-tu ROAD TO P1 à une entreprise ?','Pourquoi une marque devrait-elle suivre ton aventure ?','Comment remercierais-tu un partenaire après une course ?'],quick:['Quel est ton objectif cette saison ?','Pourquoi aimes-tu le karting ?','Quelle est ta plus grande qualité en piste ?','Quel pilote t’inspire et pourquoi ?']},en:{race:['How would you summarize your race weekend in three sentences?','What was the most difficult moment of the weekend?','What are you most satisfied with today?','What did you learn during this race?','What is your goal for the next event?'],sponsor:['What does partner support mean to your racing project?','How would you introduce ROAD TO P1 to a company?','Why should a brand follow your journey?','How would you thank a partner after a race?'],quick:['What is your main goal this season?','Why do you enjoy karting?','What is your strongest quality on track?','Which driver inspires you and why?']}};
let currentQuestion='';
function newQuestion(){const lang=$('trLang').value,format=$('trFormat').value,a=QUESTIONS[lang][format];currentQuestion=a[Math.floor(Math.random()*a.length)];$('trQuestion').textContent=currentQuestion;$('trAnswer').value='';$('trEvaluation').className='evaluation empty-eval';$('trEvaluation').textContent='Répondez puis lancez l’évaluation.';$('trBadge').textContent=`${$('trPilot').value.toUpperCase()} • ${lang.toUpperCase()}`;$('trFormatLabel').textContent=$('trFormat').selectedOptions[0].textContent}
function evaluate(){const answer=$('trAnswer').value.trim();if(!currentQuestion)return toast('Lancez d’abord une question.');if(!answer)return toast('Ajoutez une réponse.');const lang=$('trLang').value,words=answer.split(/\s+/).filter(Boolean),sent=(answer.match(/[.!?]/g)||[]).length;let clarity=Math.min(100,55+Math.min(30,sent*8)+Math.min(15,words.length/4));let concision=Math.max(45,100-Math.max(0,words.length-75)*.8);let structure=Math.min(100,50+(sent>=2?20:0)+(words.length>=20?15:0)+(words.length<=90?15:5));const fillers=lang==='fr'?['euh','bah','du coup','voilà','genre']:['um','uh','like','you know'];const hits=fillers.reduce((n,w)=>n+(answer.toLowerCase().split(w).length-1),0);let fluency=Math.max(40,92-hits*12);const avg=Math.round((clarity+concision+structure+fluency)/4);const tips=[];if(words.length<18)tips.push(lang==='fr'?'Développer davantage la réponse.':'Develop the answer a little more.');if(words.length>95)tips.push(lang==='fr'?'Raccourcir pour garder un message fort.':'Make the answer shorter and more focused.');if(sent<2)tips.push(lang==='fr'?'Structurer en 2 ou 3 idées distinctes.':'Structure the answer into 2 or 3 clear ideas.');if(hits)tips.push(lang==='fr'?'Réduire les mots de remplissage.':'Reduce filler words.');if(!tips.length)tips.push(lang==='fr'?'Bonne base : travailler maintenant le ton, le regard et le sourire.':'Good base: now work on tone, eye contact and smile.');const x={id:uid('t'),pilot:$('trPilot').value,lang,format:$('trFormat').value,question:currentQuestion,answer,scores:{clarity:Math.round(clarity),concision:Math.round(concision),structure:Math.round(structure),fluency:Math.round(fluency),avg},tips,created:now()};D.training.unshift(x);log(`Media Training • ${x.pilot} • ${lang.toUpperCase()} • ${avg}/100`);save();showEval(x);renderTraining();toast('Session enregistrée.')}
function showEval(x){$('trEvaluation').className='evaluation';$('trEvaluation').innerHTML=`<div class="score-grid"><div class="score-box"><b>${x.scores.clarity}</b><span>Clarté</span></div><div class="score-box"><b>${x.scores.concision}</b><span>Concision</span></div><div class="score-box"><b>${x.scores.structure}</b><span>Structure</span></div><div class="score-box"><b>${x.scores.fluency}</b><span>Aisance</span></div></div><p><b>Score global : ${x.scores.avg}/100</b></p>${x.tips.map(t=>`<p>• ${esc(t)}</p>`).join('')}`}
function renderTraining(){$('trCount').textContent=`${D.training.length} session${D.training.length>1?'s':''}`;$('trList').innerHTML=D.training.length?D.training.slice(0,30).map(x=>`<div class="list-item"><div><h4>${esc(x.pilot)} • ${x.lang.toUpperCase()} • ${x.scores.avg}/100</h4><div class="list-meta">${fd(x.created)} • ${esc(x.question)}</div><p>${esc(x.answer.slice(0,170))}${x.answer.length>170?'…':''}</p></div><div class="mini-actions"><button data-tr-open="${x.id}">Voir</button></div></div>`).join(''):'<div class="empty">Aucune session enregistrée.</div>';document.querySelectorAll('[data-tr-open]').forEach(b=>b.onclick=()=>{const x=D.training.find(x=>x.id===b.dataset.trOpen);if(!x)return;currentQuestion=x.question;$('trPilot').value=x.pilot;$('trLang').value=x.lang;$('trFormat').value=x.format;$('trQuestion').textContent=x.question;$('trAnswer').value=x.answer;$('trBadge').textContent=`${x.pilot.toUpperCase()} • ${x.lang.toUpperCase()}`;showEval(x);window.scrollTo({top:0,behavior:'smooth'})})}
let recognition=null;
function startMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('trHint').textContent='Reconnaissance vocale indisponible dans ce navigateur. Vous pouvez répondre au clavier.';return}stopMic();recognition=new SR();recognition.lang=$('trLang').value==='en'?'en-GB':'fr-FR';recognition.continuous=true;recognition.interimResults=false;$('trHint').textContent='Micro actif — parlez naturellement.';recognition.onresult=e=>{const text=Array.from(e.results).slice(e.resultIndex).filter(r=>r.isFinal).map(r=>r[0].transcript).join(' ');$('trAnswer').value+=( $('trAnswer').value?' ':'')+text};recognition.onerror=e=>{$('trHint').textContent='Dictée interrompue : '+e.error};recognition.onend=()=>{recognition=null};try{recognition.start()}catch(e){}}
function stopMic(){if(recognition){try{recognition.stop()}catch(e){}recognition=null}$('trHint').textContent='Dictée arrêtée. Vous pouvez corriger la réponse au clavier.'}
function bind(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>openView(b.dataset.view));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openView(b.dataset.open));$('repDate').value=today();$('repFiles').onchange=()=>{$('repFileNote').textContent=$('repFiles').files.length?[...$('repFiles').files].map(f=>f.name).join(' • '):'Aucun média sélectionné.'};$('repGenerate').onclick=()=>{$('repText').value=reportTemplate($('repPilot').value,$('repType').value,$('repEvent').value.trim(),$('repAngle').value.trim());toast('Proposition générée.')};$('repSave').onclick=saveReport;$('repSearch').oninput=renderReports;$('webSave').onclick=saveWeb;$('webPage').onchange=()=>{const o=$('webPage').selectedOptions?.[0];if(o?.dataset?.wpId){$('webPage').dataset.wpId=o.dataset.wpId;$('webPage').dataset.wpSlug=o.dataset.wpSlug||''}else{delete $('webPage').dataset.wpId;delete $('webPage').dataset.wpSlug}};$('webSync').onclick=syncWordPressPages;$('webDeployStart').onclick=openWebDeploy;$('webDeployClose').onclick=closeWebDeploy;$('webDeployCancel').onclick=closeWebDeploy;$('webDeployPrev').onclick=prevWebDeploy;$('webDeployNext').onclick=nextWebDeploy;$('webDeployModal').onclick=e=>{if(e.target===$('webDeployModal'))closeWebDeploy()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('webDeployModal').classList.contains('show'))closeWebDeploy()});$('trStart').onclick=newQuestion;$('trEvaluate').onclick=evaluate;$('trMic').onclick=startMic;$('trStop').onclick=stopMic}
load();bind();renderHome();renderReports();renderWeb();renderTraining();loadOfficialLogo();
})();
