(()=>{'use strict';
const LEVELS=['confirmed','expert','pro'];
const SOURCES={
 histoire:{label:"Histoire de l’automobile",source:"FIA / constructeurs historiques",url:"https://www.fia.com/"},
 f1:{label:"Formule 1",source:"Formula 1 / FIA",url:"https://www.formula1.com/"},
 endurance:{label:"Endurance & Le Mans",source:"24 Heures du Mans / FIA WEC",url:"https://www.24h-lemans.com/"},
 rallye:{label:"Rallye & WRC",source:"WRC / FIA",url:"https://www.wrc.com/"},
 technique:{label:"Technique & dynamique",source:"FIA — ressources techniques",url:"https://www.fia.com/"},
 karting:{label:"Karting & filière pilote",source:"FIA Karting",url:"https://www.fiakarting.com/"},
 circuits:{label:"Circuits & monuments",source:"FIA / circuits officiels",url:"https://www.fia.com/"},
 legends:{label:"Pilotes & grandes figures",source:"Formula 1 / WRC / Le Mans",url:"https://www.formula1.com/"},
 safety:{label:"Sécurité & évolution",source:"FIA Safety",url:"https://www.fia.com/safety"}
};
const RAW={
histoire:`Pionniers|Cycle Otto|En 1876, Nikolaus Otto met au point un moteur à quatre temps pratique qui donne son nom au cycle Otto.|Ce principe devient une base majeure des moteurs à allumage commandé utilisés ensuite dans l’automobile.
Pionniers|Benz Patent-Motorwagen|En 1886, Karl Benz fait breveter un véhicule conçu autour d’un moteur à combustion interne plutôt qu’une simple voiture hippomobile motorisée.|Le Patent-Motorwagen symbolise la naissance de l’automobile moderne comme système complet moteur, châssis et transmission.
Pionniers|Paris-Rouen 1894|Le concours Paris-Rouen de 1894 valorise des véhicules jugés sur leur praticité, leur sécurité relative et leur facilité d’usage, pas seulement sur la vitesse.|Cette épreuve illustre la période où la compétition sert aussi à démontrer la viabilité de technologies automobiles concurrentes.
Pionniers|Système Panhard|À la fin du XIXe siècle, Panhard et Levassor popularisent une architecture avec moteur à l’avant, boîte de vitesses et roues arrière motrices.|Cette disposition devient pendant des décennies une référence de l’architecture automobile classique.
Pionniers|Coupe Gordon Bennett|Créée en 1900, la Coupe Gordon Bennett oppose des équipes nationales et contribue à structurer les premières grandes compétitions internationales.|Elle participe notamment à l’association historique de couleurs nationales aux voitures de course.
Industrie|Ford Model T|Lancée en 1908, la Ford Model T est conçue pour être robuste, simple et produite en grand nombre à un coût progressivement réduit.|Elle devient un symbole de la démocratisation de l’automobile aux États-Unis.
Industrie|Chaîne mobile Ford|En 1913, Ford introduit à Highland Park une chaîne d’assemblage mobile qui réduit fortement le temps nécessaire à la fabrication d’un Model T.|La combinaison standardisation, spécialisation des postes et flux continu transforme la production de masse.
Industrie|Citroën Type A|En 1919, la Citroën Type A est produite en grande série en France selon des méthodes industrielles inspirées de la production américaine.|Elle marque l’essor d’une automobile européenne pensée pour une fabrication standardisée à grande échelle.
Industrie|Alfred Sloan et General Motors|Dans les années 1920, General Motors structure ses marques par niveaux de prix et développe le renouvellement régulier des modèles.|Cette stratégie montre que l’industrie automobile ne se joue plus seulement sur la technique, mais aussi sur la segmentation et le marketing.
Industrie|Toyota Production System|Après la Seconde Guerre mondiale, Toyota développe un système fondé notamment sur le juste-à-temps et le jidoka, c’est-à-dire l’arrêt du processus lorsqu’un défaut apparaît.|Cette organisation influencera largement la production industrielle moderne et le lean manufacturing.
Technique historique|Pneu pneumatique|À la fin des années 1880, John Boyd Dunlop contribue à populariser le pneu pneumatique, puis Michelin développe le pneu démontable au début des années 1890.|Le pneumatique améliore confort, adhérence et vitesse tout en devenant un élément clé du développement automobile et sportif.
Technique historique|Citroën Traction Avant|Lancée en 1934, la Traction Avant associe traction avant, carrosserie monocoque et centre de gravité relativement bas pour son époque.|Elle illustre une rupture d’architecture importante par rapport aux châssis séparés à propulsion alors très répandus.
Technique historique|Freins à disque Jaguar|Jaguar utilise avec succès les freins à disque sur la C-Type en compétition, notamment au Mans en 1953.|Le freinage à disque offre une meilleure résistance à l’échauffement et contribue ensuite à sa diffusion sur les voitures de série.
Technique historique|Mercedes 300 SL|La Mercedes-Benz 300 SL de série lancée en 1954 utilise une injection directe d’essence, technologie très avancée pour une automobile routière de l’époque.|Elle montre les transferts possibles entre recherche moteur, compétition et automobile de prestige.
Technique historique|Injection électronique|À partir de la fin des années 1960, l’injection électronique se diffuse progressivement et permet un dosage plus précis du carburant que de nombreux carburateurs.|Elle accompagne les progrès en performances, consommation et maîtrise des émissions.
Compétition|Indianapolis 500|La première édition des 500 Miles d’Indianapolis se dispute en 1911 sur l’Indianapolis Motor Speedway.|L’épreuve devient l’un des grands monuments mondiaux de la compétition automobile.
Compétition|24 Heures du Mans|Créées en 1923, les 24 Heures du Mans sont conçues comme une épreuve d’endurance capable de mettre en valeur fiabilité, efficacité et progrès techniques.|La course devient un laboratoire majeur pour les voitures de sport et les prototypes.
Compétition|Mille Miglia|La Mille Miglia naît en 1927 et se dispute sur route ouverte ou temporairement contrôlée à travers l’Italie sur environ mille miles.|Elle devient l’une des courses routières les plus célèbres avant l’arrêt de l’épreuve de vitesse après 1957.
Compétition|Grand Prix de Monaco|Le premier Grand Prix de Monaco est organisé en 1929 dans les rues de la principauté.|Son tracé urbain étroit en fait rapidement une épreuve emblématique de précision et de maîtrise.
Compétition|Carrera Panamericana|La Carrera Panamericana débute en 1950 au Mexique et devient une épreuve routière extrêmement rapide et dangereuse.|Sa courte histoire illustre autant l’attrait des grandes courses sur route que les limites de sécurité de cette époque.
Modernité|Catalyseur automobile|À partir du milieu des années 1970, les normes antipollution accélèrent notamment l’adoption du catalyseur sur de nombreux marchés.|Le contrôle des émissions devient progressivement un moteur majeur de l’évolution des moteurs et des carburants.
Modernité|ABS électronique|À la fin des années 1970, des systèmes antiblocage électroniques modernes apparaissent sur des voitures de série haut de gamme avant de se généraliser.|L’ABS vise à éviter le blocage des roues au freinage afin de préserver davantage de capacité directionnelle.
Modernité|Turbocompresseur de série|Dans les années 1970 et 1980, le turbocompresseur se diffuse sur des voitures de série pour augmenter la puissance spécifique des moteurs.|Son développement impose aussi de mieux maîtriser température, lubrification, réponse transitoire et gestion moteur.
Modernité|Toyota Prius|Commercialisée au Japon en 1997, la Toyota Prius devient la première automobile hybride produite à grande échelle.|Elle popularise l’association d’un moteur thermique et d’une chaîne électrique pour réduire la consommation dans certaines phases d’usage.
Modernité|Tesla Roadster|Lancé en 2008, le Tesla Roadster contribue à démontrer qu’une voiture électrique à batteries lithium-ion peut viser des performances élevées et une autonomie significative.|Il participe au retour de l’électrique comme projet technologique et industriel majeur au XXIe siècle.`,

f1:`Naissance du championnat|Championnat 1950|Le Championnat du monde des pilotes débute en 1950, avec Giuseppe Farina comme premier champion.|La Formule 1 existait comme réglementation, mais 1950 marque la création du championnat mondial structuré autour de plusieurs Grands Prix.
Naissance du championnat|Championnat constructeurs 1958|Le championnat du monde des constructeurs est créé en 1958, huit ans après celui des pilotes.|Il ajoute une lecture collective de la performance des équipes et des voitures sur l’ensemble de la saison.
Naissance du championnat|Indianapolis au championnat|De 1950 à 1960, les 500 Miles d’Indianapolis comptent officiellement pour le Championnat du monde des pilotes malgré des règlements et concurrents très différents.|Cette particularité rappelle que la construction du championnat mondial a connu une période de transition.
Naissance du championnat|Règlement 1,5 litre de 1961|En 1961, la F1 adopte une formule limitant les moteurs atmosphériques à 1,5 litre.|Ce changement réduit la puissance mais stimule les recherches sur légèreté, aérodynamique et efficacité du châssis.
Naissance du championnat|Points et régularité|Le système de points de la F1 a beaucoup évolué au fil des décennies, changeant la valeur relative d’une victoire, d’un podium ou d’une place d’honneur.|Comprendre une saison ancienne impose donc de replacer les résultats dans le barème de son époque.
Châssis et aérodynamique|Lotus 25 monocoque|En 1962, la Lotus 25 popularise en F1 une coque monocoque beaucoup plus rigide et compacte que les châssis tubulaires traditionnels.|La rigidité structurelle améliore la précision du comportement et ouvre la voie à la monocoque moderne.
Châssis et aérodynamique|Premiers ailerons modernes|À la fin des années 1960, les équipes exploitent des ailes pour générer de l’appui aérodynamique et augmenter la vitesse de passage en courbe.|Les premiers montages très hauts conduisent rapidement à des restrictions pour des raisons de sécurité.
Châssis et aérodynamique|Lotus 72|La Lotus 72 de 1970 combine une forme en coin, des radiateurs latéraux et une architecture très intégrée.|Elle influence durablement la manière de répartir les masses et les organes aérodynamiques sur une monoplace.
Châssis et aérodynamique|Lotus 79 et effet de sol|En 1978, la Lotus 79 exploite fortement des tunnels sous les pontons et des jupes pour créer une dépression sous la voiture.|L’effet de sol permet de générer beaucoup d’appui en utilisant le plancher comme élément aérodynamique majeur.
Châssis et aérodynamique|McLaren MP4/1 carbone|En 1981, la McLaren MP4/1 introduit en F1 une monocoque en fibre de carbone conçue comme structure principale.|Le carbone permet d’associer rigidité élevée, masse contenue et meilleure protection de la cellule pilote.
Moteurs et transmission|Cosworth DFV|Le moteur Ford-Cosworth DFV débute en F1 en 1967 et devient l’un des moteurs les plus diffusés et victorieux de l’histoire du championnat.|Sa disponibilité permet à de nombreuses équipes de construire une voiture compétitive autour d’un groupe propulseur commun.
Moteurs et transmission|Renault turbo 1977|Renault introduit le moteur turbocompressé en F1 en 1977, alors que la majorité du plateau utilise des moteurs atmosphériques.|Après des débuts difficiles, le turbo devient une voie dominante au début des années 1980.
Moteurs et transmission|Titre turbo de 1983|Nelson Piquet devient champion du monde 1983 avec une Brabham-BMW turbocompressée.|Ce titre confirme que le turbo est devenu suffisamment performant et fiable pour gagner le championnat.
Moteurs et transmission|Boîte semi-automatique Ferrari 640|En 1989, Ferrari engage la 640 avec une boîte semi-automatique commandée par palettes au volant.|Cette solution réduit le temps de changement de rapport et devient progressivement la norme en F1.
Moteurs et transmission|Ère des V10|Dans les années 1990 et au début des années 2000, l’architecture V10 s’impose largement en F1 avant l’arrivée du règlement V8 en 2006.|Elle représente un compromis recherché entre puissance, masse, consommation et encombrement.
Règlements et stratégie|Suspension active|Williams exploite avec succès la suspension active au début des années 1990, notamment avec la FW14B de 1992.|Les aides électroniques et systèmes actifs sont ensuite fortement restreints afin de reprendre le contrôle réglementaire sur la complexité technologique.
Règlements et stratégie|Ravitaillement 1994-2009|Le ravitaillement en carburant en course revient en 1994 avant d’être interdit à nouveau à partir de 2010.|Pendant cette période, la quantité de carburant embarquée et la durée des relais deviennent des paramètres stratégiques majeurs.
Règlements et stratégie|Pneus rainurés 1998|En 1998, la F1 impose des pneus secs rainurés afin de réduire l’adhérence mécanique et les vitesses de passage en courbe.|Les pneus slicks reviennent en 2009 avec un ensemble de règles aérodynamiques profondément modifié.
Règlements et stratégie|KERS 2009|Le KERS apparaît en F1 en 2009 pour récupérer de l’énergie au freinage et la restituer sous forme de puissance supplémentaire.|Il préfigure l’importance croissante de la récupération d’énergie dans les groupes propulseurs modernes.
Règlements et stratégie|DRS 2011|Le DRS est introduit en 2011 pour réduire temporairement la traînée de l’aileron arrière dans certaines conditions.|Son objectif est de faciliter les tentatives de dépassement lorsqu’une voiture suit de près une concurrente.
F1 moderne|Power units hybrides 2014|Depuis 2014, la F1 utilise des V6 turbo hybrides de 1,6 litre associés à des systèmes de récupération et de déploiement d’énergie.|La performance dépend autant de l’efficacité globale et de la gestion énergétique que de la puissance thermique brute.
F1 moderne|Halo 2018|Le halo devient obligatoire en F1 en 2018 pour renforcer la protection de la tête du pilote contre certains objets ou impacts.|Il est intégré à la cellule de survie et doit résister à des charges très élevées.
F1 moderne|Sprint 2021|La F1 introduit un format de course Sprint lors de certains week-ends à partir de 2021.|Le format évolue ensuite, mais ajoute une compétition courte distincte du Grand Prix traditionnel.
F1 moderne|Retour de l’effet de sol 2022|Le règlement 2022 remet fortement l’accent sur l’effet de sol via le plancher afin de réduire certaines turbulences générées par les ailes.|L’objectif est notamment de permettre aux voitures de se suivre plus facilement sans perdre autant d’appui.
F1 moderne|Plafond budgétaire 2021|Un plafond budgétaire entre en vigueur à partir de 2021 pour une partie des dépenses de performance des équipes.|Il cherche à limiter l’escalade des coûts tout en laissant hors plafond plusieurs postes définis par le règlement financier.`,

endurance:`Origines|Première édition 1923|Les premières 24 Heures du Mans se disputent en mai 1923 afin d’éprouver endurance, fiabilité et efficacité des automobiles.|L’épreuve s’inscrit dès l’origine dans une logique de démonstration technique sur très longue durée.
Origines|Bentley Boys|Bentley remporte plusieurs éditions du Mans à la fin des années 1920, notamment de 1927 à 1930.|Les Bentley Boys incarnent l’association entre pilotes fortunés, endurance mécanique et prestige sportif britannique.
Origines|Alfa Romeo 8C|Alfa Romeo gagne quatre fois de suite Le Mans de 1931 à 1934 avec des versions de la 8C.|Cette période montre l’importance des voitures sportives européennes avant l’interruption liée à la guerre.
Origines|Départ type Le Mans|Le célèbre départ où les pilotes couraient vers leur voiture est abandonné à la fin des années 1960, puis le départ lancé s’impose en 1971.|La sécurité et le besoin de boucler correctement les harnais rendent l’ancien rituel de moins en moins acceptable.
Origines|Accident du Mans 1955|L’accident de 1955 provoque la mort de Pierre Levegh et de nombreux spectateurs et entraîne une remise en question internationale de la sécurité en sport automobile.|Plusieurs pays suspendent ou réévaluent alors certaines compétitions tandis que circuits et règlements évoluent.
Marques et rivalités|Ferrari au début des années 1960|Ferrari domine largement Le Mans au début des années 1960 avant l’offensive de Ford.|Cette période transforme l’épreuve en affrontement industriel et sportif entre constructeurs de premier plan.
Marques et rivalités|Ford GT40|Ford remporte Le Mans pour la première fois en 1966 avec la GT40 puis gagne quatre éditions consécutives jusqu’en 1969.|Le programme illustre l’importance des moyens industriels, des essais et de la fiabilité dans une campagne d’endurance.
Marques et rivalités|Porsche 917|La Porsche 917 offre à Porsche sa première victoire au classement général du Mans en 1970 puis gagne encore en 1971.|Elle devient une icône de l’ère des prototypes très puissants du début des années 1970.
Marques et rivalités|Jaguar 1988|Jaguar remporte Le Mans en 1988 avec la XJR-9, mettant fin à une longue série de victoires Porsche.|Cette victoire marque le retour au premier plan d’un constructeur historiquement associé au Mans.
Marques et rivalités|Mazda 787B|En 1991, Mazda gagne Le Mans avec la 787B à moteur rotatif.|Il s’agit de la première victoire d’un constructeur japonais au classement général de l’épreuve.
Prototypes et règlements|Groupe C 1982|Le Groupe C lancé en 1982 impose notamment une logique de consommation de carburant plutôt qu’une simple limite de cylindrée.|Les ingénieurs doivent donc concilier vitesse, aérodynamique, stratégie et efficacité énergétique.
Prototypes et règlements|Porsche 956|La Porsche 956 exploite un plancher à effet de sol et devient l’une des références du Groupe C dans les années 1980.|Son architecture montre combien l’aérodynamique du dessous de caisse devient déterminante en endurance.
Prototypes et règlements|Ère GT1 des années 1990|Dans les années 1990, la catégorie GT1 voit apparaître des voitures très proches de prototypes malgré leur rattachement réglementaire aux GT.|Cette escalade technique conduit à des voitures comme la Mercedes CLK-GTR ou la Porsche 911 GT1.
Prototypes et règlements|Audi R8|L’Audi R8 domine une grande partie du début des années 2000 grâce à sa vitesse, sa fiabilité et une conception facilitant les interventions mécaniques.|En endurance, la rapidité de maintenance peut être aussi décisive que la performance au tour.
Prototypes et règlements|LMP1|La catégorie LMP1 devient pendant de nombreuses années le sommet des prototypes du Championnat du monde d’endurance et du Mans.|Elle rassemble des solutions très différentes en moteur, hybridation, aérodynamique et transmission avant la transition vers l’Hypercar.
Moteurs et énergie|Audi R10 TDI 2006|Audi remporte Le Mans en 2006 avec la R10 TDI, première victoire au général d’une voiture diesel.|Le diesel devient alors une voie majeure de l’endurance de haut niveau pendant plusieurs saisons.
Moteurs et énergie|Peugeot 908 2009|Peugeot gagne Le Mans en 2009 avec la 908 HDi FAP à moteur diesel.|Cette victoire interrompt la série Audi et illustre l’intense rivalité technique autour du diesel.
Moteurs et énergie|Audi hybride 2012|En 2012, l’Audi R18 e-tron quattro devient la première voiture hybride à gagner Le Mans au classement général.|L’hybridation permet de récupérer de l’énergie et de la réutiliser pour la performance et l’efficacité.
Moteurs et énergie|Porsche 919 Hybrid|La Porsche 919 Hybrid domine le Mans et le WEC au milieu des années 2010 en combinant moteur thermique et récupération d’énergie très poussée.|Cette génération LMP1 place l’efficacité énergétique au centre de la performance.
Moteurs et énergie|Toyota 2018|Toyota obtient sa première victoire au Mans en 2018 avec la TS050 Hybrid.|Le constructeur japonais concrétise alors plusieurs décennies de participation et de tentatives au plus haut niveau.
Ère Hypercar|Le Mans Hypercar 2021|La catégorie Hypercar devient la classe reine du WEC à partir de 2021 avec des règles différentes de l’ancienne LMP1.|Elle cherche à attirer davantage de constructeurs tout en maîtrisant les coûts et les performances.
Ère Hypercar|LMDh en WEC|Les prototypes LMDh deviennent éligibles au WEC et au Mans à partir de 2023 aux côtés des LMH.|Ils utilisent un châssis provenant de fournisseurs définis et un système hybride standardisé en partie.
Ère Hypercar|Balance of Performance|La Balance of Performance ajuste certains paramètres afin de rapprocher les performances de voitures conçues selon des concepts différents.|Elle est devenue un élément central du fonctionnement sportif de la catégorie Hypercar.
Ère Hypercar|Convergence WEC et IMSA|La convergence entre LMH et LMDh permet à davantage de constructeurs de viser à la fois le WEC, Le Mans et l’IMSA selon leur programme.|Elle favorise une période de forte diversité de marques au sommet de l’endurance.
Ère Hypercar|Retour massif des constructeurs|À partir de 2023, de nombreux grands constructeurs reviennent ou arrivent dans la catégorie reine de l’endurance.|Cette densité redonne au Mans une forte dimension de confrontation technologique et d’image entre marques.`,

rallye:`Origines|Rallye Monte-Carlo 1911|Le Rallye Monte-Carlo est organisé pour la première fois en 1911 avec des concurrents partant de différentes villes européennes vers Monaco.|L’épreuve naît autant comme outil de promotion touristique que comme défi automobile hivernal.
Origines|Naissance du WRC 1973|Le Championnat du monde des rallyes FIA débute en 1973 avec un championnat des constructeurs.|Le titre mondial des pilotes arrive plus tard, ce qui montre l’importance initiale accordée aux marques.
Origines|Titre pilotes 1979|Le premier véritable championnat du monde des pilotes WRC est attribué en 1979 à Björn Waldegård.|Avant cela, des coupes pour pilotes existaient mais le championnat mondial pilotes n’avait pas encore ce statut.
Origines|Spéciales et liaisons|Un rallye alterne des épreuves spéciales chronométrées et des secteurs de liaison soumis aux règles routières et horaires.|La performance dépend donc de la vitesse en spéciale mais aussi de la précision logistique sur l’ensemble de l’épreuve.
Origines|Reconnaissances|Les équipages utilisent les reconnaissances pour préparer ou vérifier leurs notes avant la compétition selon le règlement de l’épreuve.|La qualité des notes conditionne la confiance avec laquelle le pilote peut aborder des routes qu’il ne voit pas comme sur un circuit.
Révolutions techniques|Lancia Stratos|La Lancia Stratos est conçue dans les années 1970 avec la compétition rallye comme objectif central plutôt que comme simple dérivé d’une berline.|Son architecture compacte et son moteur central en font une rupture majeure dans l’histoire du rallye.
Révolutions techniques|Audi quattro|Audi engage la transmission intégrale quattro en rallye au début des années 1980 et démontre son efficacité sur surfaces à faible adhérence.|La motricité sur quatre roues change profondément la hiérarchie technique du championnat.
Révolutions techniques|Groupe B|Le Groupe B introduit au début des années 1980 des règles d’homologation permettant des voitures très puissantes et fortement spécialisées.|La liberté technique provoque une escalade rapide de puissance, d’aérodynamique et de transmission intégrale.
Révolutions techniques|Peugeot 205 T16|La Peugeot 205 T16 adopte moteur central et transmission intégrale pour le Groupe B.|Elle ne partage qu’une silhouette générale avec la 205 de série et illustre la logique très spécialisée de cette catégorie.
Révolutions techniques|Gestion du turbo|Les voitures turbo de rallye imposent de gérer réponse moteur, motricité et chaleur dans des conditions de surface très variables.|La performance ne dépend pas seulement de la puissance maximale mais de la manière dont elle est délivrée.
Après le Groupe B|Fin du Groupe B 1986|La FIA met fin au Groupe B au plus haut niveau après la saison 1986 à la suite de plusieurs accidents graves.|La sécurité devient un facteur déterminant dans la réorientation réglementaire du rallye mondial.
Après le Groupe B|Groupe A|Le Groupe A devient la référence du WRC à partir de 1987 avec des voitures plus proches de modèles produits en série.|Les volumes d’homologation plus élevés limitent les prototypes extrêmes du Groupe B.
Après le Groupe B|Lancia Delta|La Lancia Delta remporte six titres constructeurs WRC consécutifs de 1987 à 1992.|Elle symbolise la domination de Lancia au début de l’ère Groupe A.
Après le Groupe B|Subaru Impreza|La Subaru Impreza devient une icône du WRC dans les années 1990 avec sa transmission intégrale et son moteur boxer turbo.|Elle est associée aux titres constructeurs de Subaru et à des pilotes comme Colin McRae.
Après le Groupe B|Mitsubishi Lancer Evolution|La Mitsubishi Lancer Evolution domine une partie des années 1990 avec Tommi Mäkinen et une base issue du Groupe A.|Son succès montre qu’une architecture dérivée de la série peut rester extrêmement compétitive.
Ère WRC|World Rally Car 1997|Le règlement World Rally Car entre en vigueur en 1997 et assouplit certaines contraintes d’homologation par rapport au Groupe A.|Il permet aux constructeurs de développer des voitures plus spécifiquement adaptées au rallye.
Ère WRC|Sébastien Loeb|Sébastien Loeb remporte neuf titres pilotes consécutifs de 2004 à 2012.|Cette série constitue l’une des plus longues dominations individuelles de l’histoire du sport automobile.
Ère WRC|Sébastien Ogier 2021|Sébastien Ogier décroche en 2021 son huitième titre mondial des rallyes.|Ses titres obtenus avec plusieurs constructeurs illustrent une grande capacité d’adaptation à des voitures et règlements différents.
Ère WRC|Rally1 hybride 2022|La génération Rally1 introduite en 2022 associe un châssis de sécurité renforcé et, à son lancement, un système hybride aux moteurs turbo.|Cette réglementation marque une rupture technique majeure par rapport aux World Rally Cars précédentes.
Ère WRC|Rally2|La catégorie Rally2 regroupe des voitures clientes à quatre roues motrices très utilisées dans les championnats nationaux et internationaux.|Elle joue un rôle essentiel dans la progression des pilotes vers le plus haut niveau.
Organisation et pilotage|Ordre de départ sur terre|Sur terre sèche, les premières voitures peuvent balayer la couche meuble et nettoyer progressivement la trajectoire.|L’ordre de départ peut donc créer un avantage ou un désavantage selon les conditions.
Organisation et pilotage|Parc d’assistance|Le parc d’assistance concentre les interventions techniques autorisées entre certains groupes de spéciales.|Les mécaniciens travaillent sous forte contrainte de temps et doivent prioriser fiabilité et performance.
Organisation et pilotage|Super spéciale|Une super spéciale est généralement courte, spectaculaire et conçue pour rapprocher le rallye du public, parfois avec deux voitures visibles simultanément.|Elle complète les longues spéciales traditionnelles sans les remplacer.
Organisation et pilotage|Power Stage|La Power Stage, introduite en WRC en 2011, attribue des points supplémentaires sur une spéciale dédiée selon un barème qui a évolué.|Elle ajoute un enjeu de performance spécifique en fin de rallye.
Organisation et pilotage|Rôle du copilote|Le copilote lit les notes mais gère aussi temps, contrôles horaires, carnet de route et nombreuses procédures.|Son rôle associe précision sportive, navigation et gestion opérationnelle de l’équipage.`,

technique:`Pneus et adhérence|Angle de dérive|Un pneu génère une force latérale lorsqu’il travaille avec un petit écart entre la direction de la roue et la trajectoire réelle du pneu.|Cet angle de dérive vient de la déformation de la carcasse et de la gomme dans la zone de contact.
Pneus et adhérence|Cercle d’adhérence|Un pneu dispose d’une capacité limitée qu’il doit partager entre effort longitudinal de freinage ou traction et effort latéral de virage.|Plus on demande une forte accélération longitudinale, moins il reste de marge pour tourner, et inversement.
Pneus et adhérence|Sensibilité à la charge|L’adhérence d’un pneu n’augmente généralement pas proportionnellement à la charge verticale appliquée.|Le transfert de charge peut donc réduire l’adhérence totale disponible sur un essieu même si la roue extérieure est davantage chargée.
Pneus et adhérence|Pression des pneus|La pression influence forme de l’empreinte, rigidité, échauffement et réponse du pneu.|Une pression optimale dépend du pneu, de la température, de la charge, du circuit et de la durée du relais.
Pneus et adhérence|Température de pneu|La température renseigne sur le travail du pneu mais doit être interprétée avec pression, répartition intérieure-centre-extérieure et conditions de piste.|Une température élevée n’est pas automatiquement synonyme de meilleure adhérence.
Transferts et équilibre|Transfert longitudinal|Au freinage, la charge se transfère vers l’avant; à l’accélération, elle se transfère vers l’arrière.|L’amplitude dépend notamment de la hauteur du centre de gravité, de l’empattement et de l’accélération.
Transferts et équilibre|Transfert latéral|En virage, une partie de la charge verticale passe des roues intérieures vers les roues extérieures.|La répartition de ce transfert entre essieux influence l’équilibre sous-vireur ou survireur.
Transferts et équilibre|Sous-virage|Le sous-virage apparaît lorsque le train avant atteint sa limite d’adhérence relative avant le train arrière et que la voiture élargit sa trajectoire.|Il décrit un comportement global mais pas une cause unique.
Transferts et équilibre|Survirage|Le survirage apparaît lorsque le train arrière atteint sa limite relative avant l’avant et que la voiture tend à pivoter davantage que demandé.|Il peut être provoqué par le freinage, la remise de gaz, le transfert de charge ou le réglage.
Transferts et équilibre|Répartition des masses|La position des masses influence inertie, transfert de charge et vitesse avec laquelle la voiture change de direction.|Deux voitures de même masse totale peuvent avoir des comportements très différents selon la distribution de cette masse.
Aérodynamique|Appui aérodynamique|L’appui augmente la charge verticale sur les pneus sans ajouter la même masse inertielle qu’un poids supplémentaire.|Comme il dépend fortement de la vitesse, son influence devient majeure dans les courbes rapides.
Aérodynamique|Traînée|La traînée est la résistance aérodynamique qui s’oppose à l’avancement et augmente fortement avec la vitesse.|Chercher plus d’appui implique souvent un compromis avec vitesse de pointe et consommation d’énergie.
Aérodynamique|Centre de pression|Le centre de pression représente la position résultante des efforts aérodynamiques sur la voiture.|Son déplacement avec la vitesse ou l’attitude peut modifier l’équilibre entre train avant et train arrière.
Aérodynamique|Diffuseur|Un diffuseur aide à gérer l’expansion de l’air sous la voiture afin de produire de l’appui avec le plancher.|Son efficacité dépend fortement de la hauteur de caisse, de l’étanchéité aérodynamique et du flux amont.
Aérodynamique|Effet de sol|L’effet de sol utilise le plancher et des différences de pression pour générer de l’appui.|Une voiture très dépendante du plancher peut devenir sensible aux variations de hauteur et de tangage.
Châssis et suspension|Carrossage|Le carrossage est l’inclinaison de la roue vue de face et influence la manière dont le pneu travaille en virage.|Un réglage trop important peut pénaliser freinage, motricité ou usure malgré un gain potentiel en appui latéral.
Châssis et suspension|Pincement et ouverture|Le toe décrit l’orientation relative des roues vues de dessus.|Il modifie stabilité, vivacité à l’inscription et quantité de frottement générée par les pneus en ligne droite.
Châssis et suspension|Chasse|La chasse est un angle de l’axe de direction qui contribue au rappel du volant, à la stabilité et aux variations de carrossage en braquage.|Son effet dépend de toute la géométrie du train avant.
Châssis et suspension|Barre antiroulis|Une barre antiroulis couple les mouvements gauche et droit d’un essieu et modifie sa résistance au roulis.|Changer sa raideur influence la répartition du transfert de charge latéral entre avant et arrière.
Châssis et suspension|Masse non suspendue|La masse non suspendue comprend notamment une partie des roues, freins et éléments de suspension qui suivent directement les mouvements de la route.|La réduire aide généralement la roue à mieux suivre les irrégularités, mais les contraintes de rigidité et de résistance restent essentielles.
Freinage et données|Répartition de freinage|La répartition de freinage fixe la part d’effort envoyée vers l’avant et l’arrière.|Un mauvais équilibre peut provoquer blocage prématuré, instabilité ou allongement de la distance de freinage.
Freinage et données|Compression d’amortisseur|La compression contrôle la vitesse à laquelle l’amortisseur s’enfonce lors d’un transfert ou d’une bosse.|Elle influence le caractère transitoire de la voiture mais ne remplace pas le rôle du ressort.
Freinage et données|Détente d’amortisseur|La détente contrôle la vitesse à laquelle l’amortisseur se rallonge après compression.|Une détente excessive peut empêcher une roue de revenir assez vite vers sa position utile sur une succession de bosses.
Freinage et données|Rapport de transmission|Un rapport plus court augmente généralement l’accélération disponible aux roues mais réduit la vitesse atteignable pour un régime moteur donné.|Le choix doit être adapté à la plage utile du moteur et au profil du circuit.
Freinage et données|Delta télémétrique|Un delta compare l’avance ou le retard entre deux tours en fonction de la distance parcourue.|Croisé avec vitesse, frein, accélérateur et volant, il aide à localiser où le temps est réellement gagné ou perdu.`,

karting:`Châssis et délestage|Essieu arrière rigide|Un kart de compétition classique ne possède pas de différentiel sur l’essieu arrière.|En virage, le châssis doit donc permettre à la roue arrière intérieure de se délester pour limiter le ripage entre deux roues contraintes de tourner ensemble.
Châssis et délestage|Délestage de la roue intérieure|Le délestage de la roue arrière intérieure aide le kart à pivoter sans faire glisser excessivement l’essieu arrière rigide.|Trop peu de délestage fait pousser le kart; trop de délestage ou trop brutalement peut rendre le comportement instable.
Châssis et délestage|Rigidité du châssis|Un châssis de kart travaille volontairement en flexion et torsion puisqu’il ne dispose pas de suspension conventionnelle.|La rigidité recherchée dépend du grip, du pneu, du pilote et des conditions de piste.
Châssis et délestage|Rigidité de l’essieu|La rigidité de l’essieu arrière modifie la manière dont l’arrière du kart se charge, se libère et restitue l’énergie.|Son effet ne peut pas être résumé par une règle universelle plus dur ou plus tendre.
Châssis et délestage|Longueur des moyeux arrière|La longueur des moyeux contribue à la rigidité effective de l’ensemble roue-essieu.|Elle fait partie des réglages fins utilisés pour adapter le comportement de l’arrière.
Géométrie et voies|Chasse en karting|Augmenter la chasse accroît généralement l’effet de jacking qui aide à lever la roue arrière intérieure lors du braquage.|Cela peut améliorer la rotation à basse adhérence mais aussi rendre le kart plus physique ou trop agressif.
Géométrie et voies|Voie avant|La voie avant influence le levier du train avant, la réponse au braquage et la manière dont le châssis initie le délestage arrière.|Son effet doit être jugé avec la chasse, le carrossage, le pneu et le niveau de grip.
Géométrie et voies|Voie arrière|La voie arrière modifie le comportement de l’essieu rigide et la facilité avec laquelle le kart libère la roue intérieure.|Une variation de quelques millimètres peut déjà être perceptible sur un kart de compétition.
Géométrie et voies|Hauteur de caisse|Modifier la hauteur de caisse change le centre de gravité et les leviers qui participent au transfert de charge.|Un réglage utile sur piste glissante peut devenir excessif lorsque le grip augmente.
Géométrie et voies|Position du siège|La position du siège influence directement la répartition des masses et la façon dont le châssis travaille.|Elle constitue un réglage structurel important avant de chercher des corrections plus fines.
Pneus et grip|Pression à froid|La pression à froid détermine en partie la vitesse de montée en pression et en température pendant les premiers tours.|Le bon réglage dépend du pneu, de la température de piste, du poids et de la durée de la manche.
Pneus et grip|Pression à chaud|La pression à chaud reflète le résultat du travail du pneu pendant le roulage.|Comparer pression à froid, pression à chaud et chronos aide à comprendre si le pneu entre dans sa bonne fenêtre.
Pneus et grip|Température du pneu|La température doit être lue avec le comportement du kart et la pression, pas comme une valeur isolée.|Un pneu surchauffé peut perdre de la performance même si sa température semble impressionnante.
Pneus et grip|Piste gommée|Quand la piste se gomme, le niveau d’adhérence et la manière dont le kart lève sa roue intérieure évoluent.|Un réglage efficace le matin peut devenir trop contraignant ou faire sautiller le kart plus tard.
Pneus et grip|Pluie|Sous la pluie, l’objectif est de recréer de la charge et du travail mécanique dans les pneus malgré le faible grip.|Les réglages de voie, hauteur, chasse et pilotage sont souvent adaptés, mais la combinaison dépend du châssis et du pneu.
Transmission et moteur|Rapport pignon-couronne|Augmenter le nombre de dents de la couronne arrière raccourcit le rapport final pour un même pignon moteur.|Le moteur prend plus facilement des tours mais la vitesse de pointe théorique diminue à régime égal.
Transmission et moteur|Tension de chaîne|Une chaîne trop tendue augmente les pertes et les contraintes; trop lâche, elle risque de sauter ou de battre.|La tension doit rester compatible avec les déformations du châssis et l’alignement de la transmission.
Transmission et moteur|Embrayage centrifuge|Sur de nombreuses catégories modernes, l’embrayage centrifuge engage progressivement la transmission lorsque le régime moteur augmente.|Son comportement influence surtout les départs et les reprises à très basse vitesse.
Transmission et moteur|Carburation deux-temps|Sur un moteur deux-temps carburé, la richesse influence température, réponse et sécurité mécanique.|Un mélange trop pauvre peut augmenter le risque thermique tandis qu’un mélange trop riche peut dégrader la performance.
Transmission et moteur|Température d’eau|Sur un moteur à refroidissement liquide, la température d’eau aide à vérifier que le moteur travaille dans une plage cohérente.|Elle doit être interprétée avec météo, radiateur, vitesse et réglage moteur.
Pilotage et data|Freinage en kart|Le freinage modifie fortement le transfert de charge et peut aider à initier la rotation du kart.|Un relâché trop brutal ou trop tardif peut au contraire déséquilibrer l’arrière et faire perdre de la vitesse.
Pilotage et data|Volant et ripage|Un angle de volant excessif peut augmenter le ripage des pneus avant et ralentir le kart même si la trajectoire semble serrée.|Chercher la rotation avec le minimum d’angle utile est souvent un objectif de pilotage.
Pilotage et data|Vibreurs|Monter sur un vibreur peut raccourcir la trajectoire mais perturber le châssis et faire perdre du contact ou de la motricité.|Le gain dépend de la hauteur du vibreur, de l’angle d’attaque et du moment du virage.
Pilotage et data|Régime moteur en télémétrie|La courbe de régime permet de vérifier accélération, choix de rapport et chute de régime dans les virages.|Elle devient beaucoup plus utile lorsqu’elle est comparée à la vitesse GPS et au chrono par distance.
Pilotage et data|Poids minimum et lest|Le lest sert à atteindre le poids réglementaire et son emplacement influence la répartition des masses.|Il doit être solidement fixé selon le règlement et placé sans dégrader inutilement le comportement du kart.`,

circuits:`Europe historique|Monza 1922|L’Autodromo Nazionale Monza ouvre en 1922 et figure parmi les plus anciens circuits permanents encore utilisés au plus haut niveau.|Son identité reste liée aux très hautes vitesses et aux longues lignes droites.
Europe historique|Nürburgring 1927|Le Nürburgring ouvre en 1927 autour du massif de l’Eifel, avec le Nordschleife comme tracé le plus célèbre.|Sa longueur, son relief et la variété de ses virages en font une référence extrême pour pilotes et constructeurs.
Europe historique|Monaco 1929|Le Grand Prix de Monaco est organisé dans les rues de la principauté depuis 1929.|La faible largeur de piste et la proximité des barrières donnent une importance exceptionnelle à la précision.
Europe historique|Spa-Francorchamps|Le tracé historique de Spa utilisait de longues portions de routes publiques entre Francorchamps, Malmedy et Stavelot.|Le circuit moderne est beaucoup plus court mais conserve un relief marqué et des virages rapides célèbres.
Europe historique|Circuit de la Sarthe|Le circuit des 24 Heures du Mans combine une partie permanente et de longues portions de routes habituellement ouvertes à la circulation.|Cette particularité impose une préparation spécifique et crée des caractéristiques très différentes d’un circuit permanent classique.
Royaume-Uni et routes|Silverstone 1948|Silverstone accueille ses premières grandes courses en 1948 sur un ancien aérodrome militaire.|Son origine explique la largeur et la disposition initiale autour des pistes de l’aérodrome.
Royaume-Uni et routes|Goodwood 1948|Le circuit de Goodwood ouvre en 1948 sur le périmètre d’un ancien aérodrome du sud de l’Angleterre.|Il devient un haut lieu britannique avant l’arrêt des compétitions modernes sur le tracé en 1966 puis son renouveau historique.
Royaume-Uni et routes|Brands Hatch|Brands Hatch est construit dans un amphithéâtre naturel qui offre de fortes variations de relief malgré sa longueur relativement compacte.|Des virages comme Paddock Hill Bend exploitent ce relief de manière spectaculaire.
Royaume-Uni et routes|Mount Panorama|Mount Panorama à Bathurst est un circuit routier australien composé de routes publiques lorsqu’elles ne sont pas utilisées pour la compétition.|Sa section montagneuse étroite contraste fortement avec les longues lignes droites du bas du circuit.
Royaume-Uni et routes|Île de Man et culture routière|Même si le TT de l’Île de Man concerne principalement la moto, il représente la tradition britannique des grandes épreuves sur routes fermées.|Cette culture aide à comprendre l’histoire des compétitions routières avant la généralisation des circuits permanents.
Amériques|Indianapolis Motor Speedway|Indianapolis ouvre en 1909 et sa surface initiale est rapidement remplacée par des millions de briques.|Une bande de briques subsiste aujourd’hui comme symbole historique du Brickyard.
Amériques|Daytona International Speedway|Daytona ouvre en 1959 avec un tri-ovale fortement incliné conçu pour les très hautes vitesses.|Le circuit accueille notamment le Daytona 500 et les 24 Heures de Daytona sur une configuration routière.
Amériques|Watkins Glen|Watkins Glen accueille le Grand Prix des États-Unis de F1 de 1961 à 1980.|Le site devient l’un des symboles durables de la culture circuit aux États-Unis.
Amériques|Laguna Seca Corkscrew|Le Corkscrew de Laguna Seca combine un virage aveugle et une chute de dénivelé très importante.|La difficulté vient autant du placement avant la crête que du changement brutal de pente.
Amériques|Interlagos|Le circuit d’Interlagos à São Paulo ouvre en 1940 et accueille la F1 à partir de 1973.|Son sens antihoraire, son relief et son ambiance en font l’un des tracés les plus reconnaissables du championnat.
Asie et Moyen-Orient|Suzuka|Suzuka est inauguré en 1962 comme piste d’essai Honda et possède une configuration en huit avec un pont.|Son enchaînement de virages rapides en fait une référence technique pour les pilotes.
Asie et Moyen-Orient|Sepang|Le circuit de Sepang ouvre en 1999 et symbolise l’arrivée d’une génération de grands circuits modernes en Asie.|Ses longues lignes droites, ses virages variés et sa largeur favorisent plusieurs trajectoires.
Asie et Moyen-Orient|Bahrain 2004|Le Grand Prix de Bahreïn 2004 est le premier Grand Prix de F1 organisé au Moyen-Orient.|Le circuit devient ensuite un site régulier de compétition et d’essais dans la région.
Asie et Moyen-Orient|Singapore 2008|Le Grand Prix de Singapour 2008 est le premier Grand Prix de F1 disputé de nuit.|L’éclairage artificiel permet de conserver une visibilité proche du jour tout en proposant un horaire adapté à la diffusion internationale.
Asie et Moyen-Orient|Jeddah 2021|Le circuit urbain de Djeddah rejoint la F1 en 2021 avec une succession de courbes rapides le long de la corniche.|Il se distingue des circuits urbains traditionnels par sa vitesse moyenne très élevée.
Tracés modernes|Imola|Imola se parcourt dans le sens antihoraire et possède une histoire marquée par les profondes modifications de sécurité réalisées après 1994.|Le site montre comment un circuit historique peut être transformé tout en conservant une partie de son identité.
Tracés modernes|Paul Ricard|Le circuit Paul Ricard est connu pour sa longue ligne droite du Mistral et ses vastes zones de dégagement modernes.|Il a aussi longtemps servi de piste d’essais grâce à ses nombreuses configurations.
Tracés modernes|Hockenheim 2002|Hockenheim est profondément raccourci en 2002, abandonnant ses longues lignes droites forestières pour un tracé plus compact.|Cette transformation illustre l’évolution des exigences de visibilité, sécurité et exploitation commerciale.
Tracés modernes|Circuit of the Americas|Le Circuit of the Americas près d’Austin ouvre en 2012 et devient le premier circuit américain conçu spécialement pour accueillir la F1 depuis plusieurs décennies.|Il combine dénivelé important, grandes courbes et sections inspirées de caractéristiques de circuits célèbres.
Tracés modernes|Las Vegas Strip 2023|La F1 revient à Las Vegas en 2023 sur un tracé urbain passant par le Strip.|Le projet illustre la tendance moderne à intégrer de grands événements sportifs au cœur d’une destination touristique.`,

legends:`Pionniers et champions|Juan Manuel Fangio|Juan Manuel Fangio remporte cinq titres mondiaux de F1 dans les années 1950 avec plusieurs constructeurs.|Son efficacité, son adaptation et sa longévité au sommet en font une référence des débuts du championnat.
Pionniers et champions|Alberto Ascari|Alberto Ascari est champion du monde de F1 en 1952 et 1953 avec Ferrari.|Il reste l’une des grandes figures de la première décennie du championnat.
Pionniers et champions|Stirling Moss|Stirling Moss gagne de nombreux Grands Prix et grandes courses mais ne devient jamais champion du monde de F1.|Sa carrière montre qu’un palmarès ne se résume pas au nombre de titres mondiaux.
Pionniers et champions|Jim Clark|Jim Clark remporte les titres F1 1963 et 1965 et gagne aussi les 500 Miles d’Indianapolis en 1965.|Sa polyvalence sur monoplaces, voitures de tourisme et autres disciplines marque son époque.
Pionniers et champions|Jack Brabham|Jack Brabham remporte le titre F1 1966 au volant d’une voiture portant son propre nom.|Il reste le seul pilote à avoir gagné le championnat du monde avec une monoplace de sa propre marque.
F1 1960-1980|Jackie Stewart|Jackie Stewart remporte trois titres mondiaux de F1 et devient un défenseur majeur de l’amélioration de la sécurité.|Il utilise sa notoriété pour réclamer de meilleurs circuits, équipements et services médicaux.
F1 1960-1980|Niki Lauda|Niki Lauda revient en compétition quelques semaines après son grave accident du Nürburgring en 1976 puis gagne encore deux titres mondiaux.|Sa carrière associe vitesse, analyse technique et capacité exceptionnelle à revenir au plus haut niveau.
F1 1960-1980|Mario Andretti|Mario Andretti gagne en F1, en IndyCar, au Daytona 500 et dans de grandes courses de voitures de sport.|Sa carrière illustre une polyvalence devenue rare dans le sport automobile moderne.
F1 1960-1980|Gilles Villeneuve|Gilles Villeneuve ne remporte pas de titre mondial mais devient une figure mythique de Ferrari par son style spectaculaire et son engagement.|Sa réputation montre l’importance de l’impact sportif et émotionnel au-delà des statistiques.
F1 1960-1980|Nelson Piquet|Nelson Piquet remporte trois titres mondiaux de F1 en 1981, 1983 et 1987.|Son titre 1983 est aussi le premier remporté par un pilote avec un moteur turbocompressé dans l’ère moderne.
F1 moderne|Alain Prost|Alain Prost remporte quatre titres mondiaux de F1 et construit sa réputation sur la précision, la stratégie et la gestion de course.|Sa rivalité avec Ayrton Senna devient l’une des plus célèbres de l’histoire du championnat.
F1 moderne|Ayrton Senna|Ayrton Senna remporte trois titres mondiaux et six Grands Prix de Monaco.|Il est particulièrement associé à ses performances en qualification et sous la pluie.
F1 moderne|Michael Schumacher|Michael Schumacher remporte sept titres mondiaux de F1, dont cinq consécutifs avec Ferrari de 2000 à 2004.|Sa période Ferrari repose sur une organisation technique et sportive extrêmement structurée.
F1 moderne|Lewis Hamilton|Lewis Hamilton a remporté sept titres mondiaux de F1, égalant le record de Michael Schumacher.|Il détient également de nombreux records de victoires, pole positions et podiums construits sur une longue carrière.
F1 moderne|Fernando Alonso|Fernando Alonso remporte les titres F1 2005 et 2006 puis gagne deux fois les 24 Heures du Mans.|Sa carrière illustre la possibilité pour un pilote de haut niveau de performer aussi en endurance.
Rallye|Michèle Mouton|Michèle Mouton remporte quatre rallyes WRC et termine vice-championne du monde en 1982.|Elle reste la pilote féminine la plus victorieuse au plus haut niveau du championnat mondial des rallyes.
Rallye|Sébastien Loeb|Sébastien Loeb remporte neuf titres WRC consécutifs de 2004 à 2012.|Sa précision et sa constance transforment la référence statistique du rallye moderne.
Rallye|Sébastien Ogier|Sébastien Ogier remporte son huitième titre WRC en 2021 après avoir été champion avec plusieurs constructeurs.|Sa capacité à changer d’équipe et de voiture tout en restant performant marque sa carrière.
Rallye|Colin McRae|Colin McRae devient champion du monde des rallyes en 1995 avec Subaru.|Son style spectaculaire et son attaque permanente contribuent fortement à sa popularité mondiale.
Rallye|Tommi Mäkinen|Tommi Mäkinen remporte quatre titres WRC consécutifs de 1996 à 1999 avec Mitsubishi.|Il devient l’un des symboles de l’âge d’or des voitures Groupe A puis World Rally Car des années 1990.
Endurance et polyvalence|Jacky Ickx|Jacky Ickx remporte six fois les 24 Heures du Mans et gagne également plusieurs Grands Prix de F1.|Il est l’une des grandes figures reliant monoplace et endurance.
Endurance et polyvalence|Tom Kristensen|Tom Kristensen détient le record de neuf victoires aux 24 Heures du Mans.|Sa réussite couvre plusieurs générations de prototypes et de technologies.
Endurance et polyvalence|Derek Bell|Derek Bell remporte cinq fois les 24 Heures du Mans et de nombreux grands succès en voitures de sport.|Il est particulièrement associé à Porsche et à l’endurance des années 1980.
Endurance et polyvalence|Dan Gurney|Dan Gurney gagne en F1, IndyCar, NASCAR et voitures de sport, et remporte Le Mans 1967 avec A.J. Foyt.|Après cette victoire, son geste de pulvériser du champagne sur le podium devient une tradition du sport automobile.
Endurance et polyvalence|Graham Hill|Graham Hill reste le seul pilote à avoir remporté Monaco en F1, les 500 Miles d’Indianapolis et les 24 Heures du Mans.|Cet ensemble est souvent appelé la Triple Couronne du sport automobile.`,

safety:`Protection du pilote|Casque intégral|Le casque protège la tête contre les impacts, la pénétration d’objets et le feu selon des normes de plus en plus sévères.|Les homologations modernes imposent des essais mécaniques, thermiques et de visière précis.
Protection du pilote|Combinaison ignifugée|Les combinaisons, sous-vêtements, gants et chaussures homologués retardent la transmission de chaleur et de flammes.|Leur objectif est de donner au pilote davantage de temps pour sortir ou être secouru après un incendie.
Protection du pilote|Harnais multipoints|Le harnais maintient le corps dans le siège afin de répartir les charges et de limiter les mouvements violents lors d’un impact.|Son efficacité dépend du montage, du serrage et de sa compatibilité avec le siège et les autres équipements.
Protection du pilote|HANS|Le dispositif HANS limite le mouvement relatif de la tête par rapport au torse lors d’une forte décélération.|Il réduit notamment le risque de blessures graves au cou et à la base du crâne.
Protection du pilote|Halo|Le halo protège la zone supérieure du cockpit contre certains objets et impacts importants.|Son adoption en monoplace illustre une approche où la structure doit dévier ou absorber une partie de l’énergie avant qu’elle n’atteigne la tête.
Structure de la voiture|Cellule de survie|La cellule de survie doit préserver un volume résistant autour du pilote pendant que d’autres structures se déforment pour absorber l’énergie.|La sécurité moderne combine donc rigidité locale et zones sacrificielles.
Structure de la voiture|Crash-box|Une crash-box est conçue pour se déformer progressivement lors d’un impact afin de dissiper de l’énergie.|Une structure totalement rigide transmettrait des décélérations plus brutales au pilote.
Structure de la voiture|Crash tests FIA|Les monoplaces et certaines voitures de compétition doivent passer des essais d’impact et de charge avant homologation.|Ces tests transforment les objectifs de sécurité en exigences mesurables et comparables.
Structure de la voiture|Câbles de retenue de roue|Les wheel tethers cherchent à garder une roue attachée à la voiture après la rupture d’éléments de suspension.|Ils réduisent le risque qu’une roue libre devienne un projectile pour pilotes, commissaires ou spectateurs.
Structure de la voiture|Réservoir de sécurité|Les réservoirs souples de sécurité sont conçus pour mieux résister aux chocs et limiter les fuites de carburant.|Ils constituent un élément essentiel de la prévention des incendies après accident.
Circuit|Barrières TecPro|Les barrières TecPro utilisent des modules déformables destinés à absorber progressivement l’énergie d’un impact.|Elles sont souvent installées devant des structures rigides dans les zones où une sortie est possible.
Circuit|SAFER Barrier|La SAFER Barrier est largement utilisée sur les ovales nord-américains pour réduire la violence des impacts contre les murs.|Elle combine des éléments métalliques et absorbants afin d’allonger la durée de décélération.
Circuit|Bac à graviers|Un bac à graviers cherche à ralentir un véhicule sorti de piste par résistance et enfoncement des roues.|Son efficacité dépend de la vitesse, de l’angle d’entrée et du type de véhicule.
Circuit|Dégagement asphalté|Un dégagement asphalté conserve une forte capacité de freinage et permet parfois au pilote de garder davantage de contrôle.|Il peut toutefois moins pénaliser une sortie de piste et modifier le comportement des limites de piste.
Circuit|Filets et grillages|Les grillages de sécurité et filets protègent principalement le public et les zones de travail contre les débris.|Ils constituent une couche de protection supplémentaire en complément des barrières d’impact.
Procédures|Voiture de sécurité|La Safety Car regroupe le peloton à vitesse contrôlée lorsqu’un danger impose de neutraliser la course sans l’arrêter complètement.|Les procédures précisent notamment dépassements, reprise et gestion des retardataires.
Procédures|Virtual Safety Car|La VSC impose un rythme réduit contrôlé électroniquement sans regrouper toutes les voitures derrière une voiture de sécurité.|Elle vise à neutraliser rapidement la compétition tout en conservant davantage les écarts relatifs.
Procédures|Drapeau jaune|Un drapeau jaune signale un danger et impose de ralentir, avec interdiction de dépasser selon les règles applicables.|Le respect du signal est une obligation de sécurité fondamentale, même si la piste semble presque libre.
Procédures|Drapeau rouge|Le drapeau rouge arrête ou suspend la séance lorsque les conditions ne permettent plus de poursuivre normalement en sécurité.|Les voitures doivent suivre une procédure spécifique de retour et d’arrêt.
Procédures|Medical Car|La voiture médicale suit généralement le départ d’un Grand Prix de F1 et peut être déployée rapidement sur un accident.|Elle transporte du personnel et du matériel médical pour réduire le temps d’intervention.
Données et secours|Accident Data Recorder|Les enregistreurs de données d’accident mesurent des paramètres de décélération et de mouvement lors d’un choc.|Ces informations aident les ingénieurs et médecins à comprendre les mécanismes d’accident.
Données et secours|Caméras haute vitesse|Des caméras embarquées à haute fréquence d’images permettent d’étudier les mouvements très rapides de la tête et du corps pendant un impact.|Elles complètent les données numériques pour améliorer équipements et structures.
Données et secours|Extraction du pilote|Les procédures d’extraction cherchent à sortir un pilote blessé en limitant les mouvements inutiles de la colonne vertébrale.|Elles sont répétées par les équipes médicales et adaptées à la conception du cockpit.
Données et secours|Extinction incendie|Les voitures de compétition utilisent des systèmes d’extinction et les circuits disposent de moyens d’intervention spécialisés.|L’objectif est de contenir très vite un début d’incendie avant qu’il ne menace pilote ou sauveteurs.
Données et secours|Analyse systémique des accidents|La sécurité moderne étudie ensemble véhicule, circuit, équipement, procédures et intervention médicale plutôt qu’une cause isolée.|Chaque accident peut fournir des données permettant de modifier plusieurs couches de protection à la fois.`
};

function parseTheme(theme){
 const conf=SOURCES[theme], lines=RAW[theme].trim().split('\n').filter(Boolean);
 const base=lines.map((line,i)=>{
  const [subtheme,term,fact,context]=line.split('|');
  return {theme,subtheme,term,fact,context,level:LEVELS[i%LEVELS.length],source:conf.source,url:conf.url};
 });
 const groups=[...new Set(base.map(x=>x.subtheme))];
 const place=(correct,w1,w2,seed)=>{
  const pos=((seed%3)+3)%3,arr=[w1,w2];arr.splice(pos,0,correct);return {options:arr,answer:pos};
 };
 const build=(x,i,v)=>{
  const y=base[(i+7)%base.length],z=base[(i+13)%base.length];
  const wrongGroups=groups.filter(g=>g!==x.subtheme);
  let stem='',correct='',w1='',w2='',why=x.fact,detail=x.context;
  if(v===0){stem=`Quel énoncé décrit correctement « ${x.term} » ?`;correct=x.fact;w1=y.fact;w2=z.fact;}
  if(v===1){stem=`À quelle notion correspond l’énoncé suivant : « ${x.fact} » ?`;correct=x.term;w1=y.term;w2=z.term;}
  if(v===2){stem=`Quel contexte explique le mieux l’importance de « ${x.term} » ?`;correct=x.context;w1=y.context;w2=z.context;}
  if(v===3){stem=`Quelle notion faut-il associer à ce contexte : « ${x.context} » ?`;correct=x.term;w1=y.term;w2=z.term;}
  if(v===4){stem=`Quelle association est correcte à propos de « ${x.term} » ?`;correct=`${x.term} — ${x.fact}`;w1=`${x.term} — ${y.fact}`;w2=`${z.term} — ${x.fact}`;}
  if(v===5){stem=`Laquelle de ces associations est incorrecte ?`;correct=`${x.term} — ${y.fact}`;w1=`${x.term} — ${x.fact}`;w2=`${z.term} — ${z.fact}`;why=`L’association « ${x.term} — ${y.fact} » est incorrecte. ${x.fact}`;}
  if(v===6){stem=`Dans quel sous-thème classer principalement « ${x.term} » ?`;correct=x.subtheme;w1=wrongGroups[(i+1)%wrongGroups.length];w2=wrongGroups[(i+2)%wrongGroups.length];}
  if(v===7){stem=`Quel duo résume le mieux « ${x.term} » ?`;correct=`${x.fact} — ${x.context}`;w1=`${y.fact} — ${x.context}`;w2=`${x.fact} — ${z.context}`;}
  const p=place(correct,w1,w2,i+v);
  const traps=p.options.map((o,j)=>j===p.answer?'Bonne réponse.':'Cette proposition mélange ou attribue des éléments qui appartiennent à une autre notion du thème.');
  return {
   id:`v24-${theme}-${String(i+1).padStart(2,'0')}-${v+1}`,
   subtheme:x.subtheme,level:x.level,q:stem,options:p.options,answer:p.answer,
   why, dossier:`${x.fact} ${x.context}`,
   key:[x.term,x.fact,x.context],
   traps,
   follow:`Explique avec tes propres mots pourquoi « ${x.term} » est important dans le thème « ${SOURCES[theme].label} ».`,
   source:x.source,url:x.url
  };
 };
 const questions=[];
 base.forEach((x,i)=>{for(let v=0;v<8;v++)questions.push(build(x,i,v));});
 return {questions,subthemes:groups,conceptCount:base.length,target:200};
}
const questions={},curriculum={};
Object.keys(RAW).forEach(theme=>{const p=parseTheme(theme);questions[theme]=p.questions;curriculum[theme]={subthemes:p.subthemes,conceptCount:p.conceptCount,target:p.target};});
window.RTP1_CULTURE_V24={version:'2.4',targetPerTheme:200,questions,curriculum};
})();